# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: \\.coverage.*
default_language_version:
  python: python3.9

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false

repos:
  - repo: local
    hooks:
      - id: black
        name: "Black"
        entry: black --check
        language: system
        types: ["file", "python", "text"]

      - id: flake8
        name: "Flake8"
        entry: flake8
        language: system
        types: ["file", "python", "text"]

      - id: isort
        name: "isort"
        entry: isort --check --filter-files
        language: system
        types: ["file", "python", "text"]