name: Fetch Data

on:
  schedule:
    # Normal schedule
    # # at 01:15 on all days in first month of each quarter
    # - cron: '15 1 * 1,4,7,10 *'
    # Temp schedule
    # at 01:15 on all days in all months
    - cron: '15 1 * * *'

  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    env:
      GCS_DEVELOPER_KEY: ${{ secrets.GCS_DEVELOPER_KEY }}
      GCS_CX: ${{ secrets.GCS_CX }}

    # CC Technology team members:
    #   See cc-quantifying-bot GitHub entry in Bitwarden for information on
    #   BOT_ secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv sync --system

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=./scripts" >> $GITHUB_ENV

      - name: Run fetch script
        run: |
          ./scripts/1-fetch/gcs_fetched.py \
            --enable-git --enable-save --limit=100
