name: Process Data

on:
  # push:
  schedule:
    # 1:15am onwards, days 1-20, second month of each quarter
    - cron: '15 1,5,9,13,17,21,23 1-20 2,5,8,11 *'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv sync --system

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=./scripts" >> $GITHUB_ENV

      - name: Run process script
        run: |
          python scripts/2-process/gcs_processed.py

      - name: Fetch and merge changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/shared.py --operation fetch_and_merge --branch fetch-automation

      - name: Add and commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/shared.py --operation add_and_commit --message "Automated data processing and commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/shared.py --operation push
